### ISSUE TITLE
bug: throws error with NextJS projects PROD build

### ISSUE THREAD

**Issue by vibbs** [docarys/markdown-it-admonition#13]
## Project Environment:
```
    "next": "latest",
    "react": "^18.2.0",
    "markdown-it": "^13.0.1",
    "markdown-it-admonition": "^1.0.4",
```

## Actual Error: 

```console
ReferenceError: renderDefault is not defined
    at e.exports (_app-23f57b3fd9b2f356.js:5:59129)
    at b.use (_app-23f57b3fd9b2f356.js:5:69113)
    at 2897 (_app-23f57b3fd9b2f356.js:6:189961)
    at l (webpack-c3b73243e73fbc73.js:1:167)
    at 3511 (_app-23f57b3fd9b2f356.js:6:4590)
    at l (webpack-c3b73243e73fbc73.js:1:167)
    at 3847 (_app-23f57b3fd9b2f356.js:6:180688)
    at l (webpack-c3b73243e73fbc73.js:1:167)
    at _app-23f57b3fd9b2f356.js:6:2058
    at main-90a34299418a0f2b.js:1:22840
```

I am not sure why this fails in the PROD build but functions fine in the DEV build. Basically, it has to do with how NextJS is building the project.

--- 

Possible solution:

Reordering the code where definitions are at the top and references usages comes after something along these lines:
```js
function defaultX() {
 console.log("func default x");
}

var x = defaultX;

```

instead of 
```js
var x = defaultX;

function defaultX() {
 console.log("func default x");
}



```

**Comment by vibbs** [comment]
PR which takes care of the above issue: 

https://github.com/docarys/markdown-it-admonition/pull/14
